title = "math-for-cs"

[project]
reponame = "math-for-cs"
title = "Math for CS"
description = "Math by bullet point"
tags = ["math", "math.dm", "math.lo", "math.cs"]
discipline = "math"
type = "notes"


[remotes]
name = "GitBook"
url = "https://github.com/"


[author]
name = "Ilic Ivan"
email = "ilicivan@zoho.com"
homepage = "https://github.com/mandober"
